[package]
name = "shv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = { git = "https://github.com/fvacek/rust-simple_logger.git", branch = "main", features = ["stderr"] }

futures = "0.3.29"
async-std = { version = "1.12.0", features = ["attributes"] }
log = "0.4.20"
bytes = "1.5.0"
sha1 = "0.10.6"
chrono = "0.4.31"
hex = "0.4.3"
rand = "0.8.5"
url = "2.4.1"
#percent-encoding = "2.3.0"
glob = "0.3.1"
duration-str = "0.7.1"
serde = "1.0.193"
serde_yaml = "0.9.29"
clap = { version = "4.4.12", features = ["derive"] }
async-trait = "0.1.77"

[[bin]]
name = "cp2cp"
[[bin]]
name = "shvcall"
[[bin]]
name = "shvbroker"
