name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    strategy:
      matrix:
        toolchain:
          - channel: stable
            cargo_args: --verbose --all-targets
          - channel: nightly
            cargo_args: --verbose --all-targets --all-features

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup toolchain
      run: >
        rustup update ${{ matrix.toolchain.channel }} &&
        rustup default ${{ matrix.toolchain.channel }} &&
        rustup component add clippy
    - name: Clippy
      run: cargo clippy ${{ matrix.toolchain.cargo_args }}
    - name: Build
      run: cargo build ${{ matrix.toolchain.cargo_args }}
    - name: Run tests
      run: cargo test ${{ matrix.toolchain.cargo_args }} -- --test-threads=1
